#!/usr/bin/env python2
# vim: ft=python

''' Bjorn Pieper. June 2016 '''

from argparse import ArgumentParser
from sys import argv, exit
from re import search
from subprocess import check_output 
from itertools import chain
import gzip

p = ArgumentParser(prog='sdi2snp', description='Produce a SNP table out of an'+\
                   ' arbitrary bunch of sdi files, which may be in the'+\
                   ' form of gzip archives. This may take quite a while'+\
                   ' when many sdi files are processed and it will need'+\
                   ' lots of memory too (eg. 14Gb for 80 A.thaliana sdi)!')
p.add_argument('-sdi', metavar='<String>', help='Path containing the sdi files',
               required=True)
p.add_argument('-l', metavar='<String>', help='list of files to process and'+\
               ' that relates file names to strain names. Use -fcol and'+\
               ' -scol to indicate the respective column numbers in the'+\
               ' list (defaults to columns 1 and 2).i\n'+\
               ' The file extensions (.sdi or .sdi.gz) are not required to '+\
               ' be included in the file names column.\nWhen -l is omitted'+\
               ' the file names themselves minus extensions will be used as'+\
               ' strain names, and all sdi files in the path will be processed', 
               required = False)
p.add_argument('-ld', metavar='<String>', help='Delimiter in \'-l\'. Default'+\
               ' delimiter is TAB. Use quotes to indicate a whitespace like: '+\
               '\' \'.', required=False, default='\t') 
p.add_argument('-fcol', metavar='<Int>', help='Number of the column in \'-l\''+\
               ' containing the sdi file names.', required=False, default=1,
               type=int)
p.add_argument('-scol', metavar='<Int>', help='Number of the column in \'-l\''+\
               ' containing the strain names', required=False, default=2,
               type=int)
p.add_argument('-ref', metavar='<String>', help='Name of the reference strain'+\
               ' used for the alignment in the sdi files', required=True)
p.add_argument('-chr', metavar='<String>', help='Provide the value of the '+\
               'chromosome to process as it occurs in the sdi files', 
               required=True)
p.add_argument('-f', help='Indel filtering. By default indel alleles for '+\
               'sites that are SNPs for other strains are converted to N. By '+\
               'providing this flag these sites will be excluded entirely.',
               required=False, action='store_true')
p.add_argument('-out', metavar='<string>', help='Output file name', 
               required=True)
p._optionals.title='options'

if len(argv) == 1:
    p.print_help()
    exit(0)

args = p.parse_args()

if not args.sdi[-1] == '/': args.sdi = args.sdi + '/'

## Select sdi files
ls = [ i for i in check_output(['ls', args.sdi]).split('\n') if search('sdi', i) ]
rel = [ i.split(args.ld) for i in open(args.l).read().split('\n')[:-1] ]
files = [ ( i, [j[args.scol-1] for j in rel if
            j[args.fcol-1] == i.strip('.sdi.gz')][0] )
          for i in ls if i.strip('.sdi.gz') in
          [j[args.fcol-1] for j in rel] ]

## List of file objects
handler = [ gzip.open(args.sdi + j[0]) for j in files if search('gz', j[0]) ] +\
          [ open(args.sdi + j[0]) for j in files if not search('gz', j[0]) ]  
h_iter = xrange(len(handler))
length = len(h_iter)

## Funtions
def getData(handler, args_f, h_iter, args_chr, length, 
            dat = None):
    if dat is None:
        dat = getData_start(handler, args_chr, h_iter)    
    else:
        dat[0] = [ dat[0][i] if not dat[1][i] else 
                   handler[i].readline().split('\t')
                   for i in h_iter ]
    dat[0] = [dat[0][i] if len(dat[0][i]) > 4 else
              ('END', '999999999', '-1', 'X', 'X') for i in h_iter]
    chrpos = [(i[0], int(i[1])) for i in dat[0]]
    minpos = min([i[1] for i in chrpos])
    dat[1] = [True if chrpos[i][1] == minpos and chrpos[i][0] == args_chr
                   else False for i in h_iter]
    if sum(dat[1]) == 0: return None
    zero = [dat[0][i][2] for i in h_iter if dat[1][i]]
    if '0' not in zero or (args_f and zero.count('0') != len(zero)):
        dat = getData(handler, args_f, h_iter, args_chr, length, dat)
    return dat 

def getData_start(handler, args_chr, h_iter,
                  cdat = [[None for i in h_iter],
                  [True for i in h_iter]]):
    while True:
        cdat[0] = [ cdat[0][i] if not cdat[1][i] else
                    handler[i].readline().split('\t')
                    for i in h_iter ]
        cdat[1] = [cdat[0][i][0] != args_chr for i in h_iter]
        if sum([len(i) for i in cdat[0]]) == 0:
            exit(args_chr + ' not found in the sdi tables!')
        if sum(cdat[1]) == 0:
            return cdat

def findRef(x):
    for i in x:
        if i[2] == '0':
            return i[3]

def maskIndel(aux):
    minpos = min([int(i[1]) for i in aux[0]])
    for i, j in enumerate(aux[0]):
        if int(j[1]) == minpos and j[2] != '0':
            aux[0][i][4] = 'N'
            aux[1][i] = True 
    return aux

## Make the table
with open(args.out, 'wb') as out:
    out.write('\t'.join(['chromosome', 'position', args.ref] + 
                        [i[1] for i in files]) + '\n')

    while True:
        if 'data' not in locals() or 'data' not in globals():
            data = getData(handler,args.f, h_iter, args.chr, length)
        else:
            data = getData(handler,args.f, h_iter, args.chr, length, data)
        
        if data is None: break

        if not args.f:
            data = maskIndel(data)

        ref = findRef([data[0][i] for i in h_iter if data[1][i]])    
        pos = data[0][[i for i in h_iter if data[1][i]][0]][1] 
        res = [args.chr, pos, ref] + [ data[0][i][4] if data[1][i] else ref
                                       for i in h_iter ]
        out.write('\t'.join(res) + '\n') 
