#!/usr/bin/python

''' Bjorn Pieper, Dec-07 2015, MPIPZ Cologne.
    tped and tfam from SNPs for arbitrary regions.
'''

from subprocess import call
from sys import exit, argv
from getopt import gnu_getopt, GetoptError
from random import normalvariate

def TPEDTFAM(vCHR, vPOS5, vPOS3, vOUTPUT, vPHEN, vFILTER, vEXCLUDE):

  path = '/biodata/dep_tsiantis/common/Bjorn/Ch190_database/SNP_tables_Ch190/'
  composite1 = '$2>=' + str(vPOS5) + ' && $2<=' + str(vPOS3)
  with open('.snp2tpedtfam_temp', 'w') as outfile:
    call(['awk', composite1, path + vCHR + '_Ch190_SNP_newVar'], stdout=outfile)

## Load SNP data
  with open(path + vCHR + '_Ch190_SNP_newVar', 'r') as getheader:
    snps_header = [ x.strip('\n') for x in getheader.readline().split('\t') ]
  with open('.snp2tpedtfam_temp', 'r') as SNPs:
    snps = [ [ x.strip('\n') for x in y.split('\t') ] for y in SNPs ]

  strains = [ x.strip('\n') for x in snps_header if x not in ['chromosome', 'position'] + vEXCLUDE ]
  current = [[] for x in strains]
  positions = []
  if len(vPHEN) == 0: 
    print 'generating normally distributed random phenotypic data with mean 1 and sigma 0.25'
    vPHEN = [ max(0, normalvariate(1, 0.25)) for x in strains] # cap at 0 just in case to prevent negative numbers
  if not len(vPHEN) == len(strains):
    exit('ERROR: ' + str(len(vPHEN)) + 'phenotypic observations provided yet ' + str(len(strains)) + ' accessions included!')

  for x in range(len(snps)-1):
    
    positions.append(snps[x][1])
    
    for y in strains:
      if vFILTER == True:
        if snps[x][snps_header.index(y)] not in ['A', 'G', 'C', 'T', 'N']:
          snps[x][snps_header.index(y)] = 'N'
      current[strains.index(y)].append(snps[x][snps_header.index(y)])

  with open(vOUTPUT + '.tfam', 'wb') as output:
    counter = 1
    for x in strains:
      output.write(str(1) + '\t' + str(counter) + '\t' + '\t'.join(['0', '0', '0']) + '\t' + str(vPHEN[strains.index(x)]) + '\n')
      counter += 1

  with open(vOUTPUT + '.tped', 'wb') as output:
    for x in positions:
      output.write(str(1) + '\t' + vCHR + '_' + str(x) + '\t' + str(x) + '\t' +'\t'.join([y + '\t' + y for y in [z[positions.index(x)] for z in current]]) + '\n')

  call([ 'rm', '.snp2tpedtfam_temp' ])

def HELP():
  print 'example:\n\tsnp2tpedtfam -c Chr1 -5 5000 -3 12500 -f -o fastac1 -p /home/johnny/phenotypes.tbl -x Ox wa jap\n'
  print '-h\tgive this help massage'
  print '-c\tchromosome [eg. Chr1] <required>'
  print '-p1\t5\' position <required>'
  print '-p2\t3\' position <required>'
  print '-f\tconvert ambiguous base calls to \'N\' [omit for default (do not filter)] <optional>'
  print '-o\toutput file name. Do not provide a file extension; three files are produced:\n\t(1) a tped file (.tped), (2) a tfam file with random phenotype is none was provided (.tfam),\n\tand (3) a list of included accessions (.acc) <required>'
  print '\p\tphenotypic data. A file with a column of accession names and a column of phenotypes.\n\tIf none is provided normally distributed data with mean 0 and sigma 0.25 will be generated. <optional>'
  print '-x\taccessions to exclude [multiple possible when separated by white space]\n\tThis option must be provided last!!!'

def main(argv):
  vCHR = ''
  vPOS5 = ''
  vPOS3 = ''
  vOUTPUT = ''
  vEXCLUDE = []
  vFILTER = False
  vPHEN = ''
  exopt = 9
  try:
    opts, args = gnu_getopt(argv,"hc:5:3:fo:px")
    if not opts: exit(HELP())
  except GetoptError:
    print 'example:\n\tsnp2tpedtfam [-h] -c Chr1 -5 5000 -3 12500 -f -o fastac1 -p /home/johnny/phenotypes.tbl -x Ox wa jap>'
    exit(2)
  for opt, arg in opts:
    if opt == '-h':
      HELP()
      exit()
    elif opt in ("-c"):
      vCHR = arg
    elif opt in ("-5"):
      vPOS5 = arg
    elif opt in ("-3"):
      vPOS3 = arg
    elif opt in ("-f"):
      vFILTER = True
      exopt = exopt + 1 
    elif opt in ("-o"):
      vOUTPUT = arg
    elif opt in ("-p"):
      vPHEN = arg
      exopt = exopt + 2 
    elif opt in ("-x"):
      vEXCLUDE = [x for x in argv[exopt:]]
  
  TPEDTFAM(vCHR, vPOS5, vPOS3, vOUTPUT, vPHEN, vFILTER, vEXCLUDE)

if __name__ == "__main__":
   main(argv[1:])

